### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by max3903** [akretion/odoo-elasticapm#4]
Using Python 3.8 and Odoo 14, I get the following error when starting Odoo with odoo-elasticapm:

```
app_1   | 2021-11-26 18:42:08,014 103 ERROR ? elasticapm.utils.threading: Exception in interval timer function 
app_1   | Traceback (most recent call last):
app_1   |   File "/usr/local/lib/python3.8/dist-packages/elasticapm/utils/threading.py", line 84, in run
app_1   |     rval = self._function(*self._args, **self._kwargs)
app_1   |   File "/usr/local/lib/python3.8/dist-packages/elasticapm/conf/__init__.py", line 742, in update_config
app_1   |     new_version, new_config, next_run = self.transport.get_config(self.config_version, keys)
app_1   |   File "/usr/local/lib/python3.8/dist-packages/elasticapm/transport/http.py", line 154, in get_config
app_1   |     response = self.http.urlopen(
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
app_1   |     response = conn.urlopen(method, u.request_uri, **kw)
app_1   |   File "/usr/local/lib/python3.8/dist-packages/elasticapm/instrumentation/packages/base.py", line 205, in call_if_sampling
app_1   |     return wrapped(*args, **kwargs)
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
app_1   |     httplib_response = self._make_request(
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
app_1   |     conn.request(method, url, **httplib_request_kw)
app_1   |   File "/usr/lib/python3.8/http/client.py", line 1252, in request
app_1   |     self._send_request(method, url, body, headers, encode_chunked)
app_1   |   File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
app_1   |     self.endheaders(body, encode_chunked=encode_chunked)
app_1   |   File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
app_1   |     self._send_output(message_body, encode_chunked=encode_chunked)
app_1   |   File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
app_1   |     self.send(msg)
app_1   |   File "/usr/lib/python3.8/http/client.py", line 947, in send
app_1   |     self.connect()
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
app_1   |     conn = self._new_conn()
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
app_1   |     conn = connection.create_connection(
app_1   |   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
app_1   |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
app_1   |   File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
app_1   |     addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
app_1   |   File "/usr/lib/python3/dist-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
app_1   |     return self.pool.apply(_socket.getaddrinfo, args, kwargs)
app_1   |   File "/usr/lib/python3/dist-packages/gevent/pool.py", line 159, in apply
app_1   |     return self.spawn(func, *args, **kwds).get()
app_1   |   File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
app_1   |   File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
app_1   |   File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
app_1   |   File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
app_1   |   File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
app_1   |   File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 371, in g
app_1   |     return f(a)
app_1   |   File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 432, in load_traceback
app_1   |     return loads(s)
app_1   |   File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 337, in unpickle_traceback
app_1   |     return ret.as_traceback()
app_1   |   File "/usr/lib/python3/dist-packages/gevent/_tblib.py", line 202, in as_traceback
app_1   |     code = CodeType(
app_1   | TypeError: an integer is required (got type bytes)
```

**Comment by syntakz** [comment]
any solution for this question ?
I face same problem here
odoo14 using python3.8 (3.6 before was no problem)
